version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - mynetwork
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=unreal_go
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - mynetwork
networks:
    mynetwork:
volumes:
    db_data:
