version: '3'
services:
    unrealgo-app:
        container_name: unrealgo_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - '80:80'
        volumes:
            - .:/var/www
        env_file:
            - .env
        depends_on:
            - unrealgo-db
        networks:
            - unrealgo_network
    unrealgo-redis:
        image: 'redis:latest'
        container_name: unrealgo_redis
        networks:
            - unrealgo_network
    unrealgo-db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: unreal_go
        container_name: unrealgo_mysql
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - unrealgo_network
networks:
    unrealgo_network:
volumes:
    db_data:
