name: SetUP to Production

on:
  push:
    branches:
      - unreal-go.top

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
          fetch-depth: 2
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.prod', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 'v16.10.0'
      - name: 🔨 Install Dependecies
        run: npm install
      - name: 🔨 Build Project
        run: npm run prod

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Ftp-deploy RES
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          server-dir: "projects/production/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/public/**
            **/vendor/**
      - name: Ftp-deploy PUBLIC
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: "./public/"
          server-dir: "unreal-go.top/"

